{% set name = "gflanguages" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gflanguages-{{ version }}.tar.gz
  sha256: 46c7c48987c959974228b2a58a980e8f7b5b54285d22e3c122f3cf7021e4bc2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=4,<6.1
  run:
    - protobuf =3.19.4
    - python >=3.7

test:
  imports:
    - gflanguages
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/gflanguages/
  summary: A python API for evaluating language support in the Google Fonts collection.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
